# -*- coding: utf-8 -*-
"""Copy of gen_ai_day_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1airdtC10Q-H8qOQS-RrqQt_e-VbqWygF
"""

from transformers import pipeline

generator=pipeline('text-generation',model='openai-community/gpt2')

output=generator("AI will revolutionise",repetition_penalty=1.5)

print(output[0]['generated_text'])

generator = pipeline("text-generation", model="gpt2-medium")


output = generator("Explain quantum computing:",
                  num_return_sequences=1,
                  temperature=0.7,
                   repetition_penalty=1.5)
print(output[0]['generated_text'])

from transformers import pipeline
def generated_text(prompt):
  generator = pipeline("text-generation", model="gpt2-medium",repetition_penalty=1.5)
  return generator(prompt, max_length=200)[0]['generated_text']

while True:
  user_input=input("Enter a prompt or quit to exit: ")
  if user_input.lower()=='quit':
    break
  print("\n"+generated_text(user_input))

# Using gpt2-medium + repetition_penalty for better quality
# Will learn advanced tuning in Month 4 (LoRA/fine-tuning)